class CreateStudents < ActiveRecord::Migration[5.1]

  def change
    create_table :students do |t| #added the create_table method and passed the name of the table we want to create as a symbol
      t.string :name
      #on the left we've given the data type we'd like to cast the column as, and on the right we've given the name we'd like to give the column
      #primary key will be automatically generated by ActiveRecord
    end
  end

end
